version: "3.8"

services:
  tg-publisher:
    build: .
    restart: unless-stopped
    volumes:
      - onepostbot_data:/app/data
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"

volumes:
  onepostbot_data:
    name: onepostbot-stack-7gdtph_onepostbot_data
    external: true

networks:
  internal:
    driver: bridge
